// Static seed data — single source of truth for the catalog
export const CATEGORIES = [
  { slug: 'sap-btp', name: 'SAP BTP', icon: '☁️', color: 'from-sky-500 to-blue-600', count: 8, featured: true },
  { slug: 'sap-cpi', name: 'SAP Integration Suite', icon: '🔗', color: 'from-indigo-500 to-blue-500', count: 12, featured: true },
  { slug: 'sap-abap', name: 'SAP ABAP', icon: '⚡', color: 'from-blue-500 to-purple-500', count: 9, featured: true },
  { slug: 'sap-fiori', name: 'SAP Fiori / UI5', icon: '🎨', color: 'from-violet-500 to-indigo-500', count: 7, featured: true },
  { slug: 'sap-successfactors', name: 'SuccessFactors', icon: '👥', color: 'from-pink-500 to-rose-500', count: 6, featured: true },
  { slug: 'sap', name: 'SAP S/4HANA', icon: '🏢', color: 'from-blue-500 to-cyan-500', count: 10, featured: true },
  { slug: 'ai', name: 'AI & GenAI', icon: '🧠', color: 'from-purple-500 to-pink-500', count: 18 },
  { slug: 'aws', name: 'AWS', icon: '☁️', color: 'from-orange-500 to-yellow-500', count: 14 },
  { slug: 'azure', name: 'Azure', icon: '🔷', color: 'from-blue-600 to-indigo-600', count: 9 },
  { slug: 'devops', name: 'DevOps', icon: '⚙️', color: 'from-green-500 to-emerald-500', count: 11 },
  { slug: 'python', name: 'Python', icon: '🐍', color: 'from-yellow-500 to-orange-500', count: 15 },
  { slug: 'react', name: 'React', icon: '⚛️', color: 'from-cyan-400 to-blue-500', count: 10 },
]

// Indian professional avatars
const AV = {
  rajesh: 'https://images.unsplash.com/photo-1597202992582-9ee5c6672095?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxODd8MHwxfHNlYXJjaHw0fHxpbmRpYW4lMjBzb2Z0d2FyZSUyMGVuZ2luZWVyfGVufDB8fHx8MTc4NTA1MTAyN3ww&ixlib=rb-4.1.0&q=85&w=200',
  suresh: 'https://images.unsplash.com/photo-1742981365880-698cfb84492d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1Mjh8MHwxfHNlYXJjaHwxfHxpbmRpYW4lMjBidXNpbmVzc21hbnxlbnwwfHx8fDE3ODUwNTEwMjd8MA&ixlib=rb-4.1.0&q=85&w=200',
  aditya: 'https://images.unsplash.com/photo-1771244688590-1e481dba1b5a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1Mjh8MHwxfHNlYXJjaHwzfHxpbmRpYW4lMjBidXNpbmVzc21hbnxlbnwwfHx8fDE3ODUwNTEwMjd8MA&ixlib=rb-4.1.0&q=85&w=200',
  vikram: 'https://images.pexels.com/photos/7580822/pexels-photo-7580822.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=200',
  arjun: 'https://images.unsplash.com/photo-1649433658557-54cf58577c68?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwyfHxpbmRpYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdHxlbnwwfHx8fDE3ODQ5MDIwMzJ8MA&ixlib=rb-4.1.0&q=85&w=200',
  karthik: 'https://images.pexels.com/photos/7580948/pexels-photo-7580948.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=200',
  priyaS: 'https://images.unsplash.com/photo-1659353220597-71b8c6a56259?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNDR8MHwxfHNlYXJjaHwzfHxpbmRpYW4lMjBidXNpbmVzc3dvbWFufGVufDB8fHx8MTc4NTA1MTA0NXww&ixlib=rb-4.1.0&q=85&w=200',
  anjali: 'https://images.pexels.com/photos/7581115/pexels-photo-7581115.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=200',
  meera: 'https://images.unsplash.com/photo-1637589267610-6c66fc2a086b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNDR8MHwxfHNlYXJjaHwxfHxpbmRpYW4lMjBidXNpbmVzc3dvbWFufGVufDB8fHx8MTc4NTA1MTA0NXww&ixlib=rb-4.1.0&q=85&w=200',
  divya: 'https://images.pexels.com/photos/7580837/pexels-photo-7580837.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=200',
  kavya: 'https://images.unsplash.com/photo-1778692258270-bc0e80e975c0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwzfHxpbmRpYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdHxlbnwwfHx8fDE3ODQ5MDIwMzJ8MA&ixlib=rb-4.1.0&q=85&w=200',
}

const mkLesson = (id, title, duration, free = false, type = 'video') => ({
  id, title, duration, free, type,
  videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  transcript: `In this lesson we cover ${title}. You'll learn the fundamentals, best practices, and see practical examples. By the end of this module you'll be able to apply these concepts in real-world scenarios.`,
  resources: [
    { name: 'Lesson Slides.pdf', size: '2.4 MB', type: 'pdf' },
    { name: 'Source Code.zip', size: '1.1 MB', type: 'zip' },
    { name: 'Cheat Sheet.pdf', size: '480 KB', type: 'pdf' },
  ]
})

const mkCurriculum = (modules) => modules.map((m, i) => ({
  id: `m${i+1}`,
  title: m.title,
  lessons: m.lessons.map((l, j) => mkLesson(`m${i+1}l${j+1}`, l[0], l[1], l[2] || (i===0 && j<2)))
}))

export const COURSES = [
  {
    slug: 'sap-btp-complete-mastery',
    title: 'SAP BTP — Complete Platform Mastery (2025 Edition)',
    subtitle: 'Master Business Technology Platform: CAP, Fiori, HANA Cloud, Kyma & Integration',
    category: 'sap-btp', categoryName: 'SAP BTP',
    level: 'Advanced', language: 'English + Hindi',
    duration: '48h', lectures: 124, students: 6820, rating: 4.9, reviews: 1240,
    price: 15999, originalPrice: 34999, discount: 55,
    thumbnail: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    banner: 'https://images.unsplash.com/photo-1591439657848-9f4b9ce436b9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHw0fHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Flagship','Live Batches'], badge: 'Flagship',
    description: 'The most comprehensive SAP Business Technology Platform course ever built. Master every BTP pillar — CAP, HANA Cloud, Kyma, Integration Suite, Fiori, Workflow, AI Core — with 8 enterprise-grade capstone projects. Explained in English + Hindi hybrid.',
    whatYouLearn: [
      'Architect end-to-end BTP solutions for enterprise scenarios',
      'Build side-by-side extensions with SAP CAP (Cloud Application Programming)',
      'Deploy microservices on Kyma runtime with Kubernetes',
      'Design HANA Cloud data models and calculation views',
      'Integrate S/4HANA, SuccessFactors, Ariba with Integration Suite',
      'Consume SAP AI Core & Business AI in your apps',
      'Implement authentication with XSUAA, IAS, and OAuth 2.0',
      'Master BTP cockpit, subaccounts, entitlements & cost management',
    ],
    skills: ['SAP BTP','CAP','HANA Cloud','Kyma','Integration Suite','Fiori','XSUAA','AI Core'],
    instructor: { name: 'Rajesh Kumar', title: 'Principal SAP Architect · SAP Mentor · Bengaluru', avatar: AV.rajesh, rating: 4.9, students: 28400, courses: 8, bio: '18 years architecting SAP for Fortune 500. Ex-SAP Labs Bengaluru. Official SAP Mentor.' },
    curriculum: mkCurriculum([
      { title: 'BTP Foundations & Architecture', lessons: [['What is BTP: Platform Overview','12:20'],['Multi-Cloud Landscape (AWS/Azure/GCP)','24:15'],['Subaccounts, Directories & Entitlements','28:40'],['BTP Cockpit Deep Dive','22:10']] },
      { title: 'SAP CAP — Cloud Application Programming', lessons: [['CAP Fundamentals','32:20'],['CDS Data Modeling','44:15'],['Building Services in Node.js','48:40'],['Deploying to Cloud Foundry','28:20']] },
      { title: 'HANA Cloud & Data Modeling', lessons: [['HANA Cloud Architecture','32:12'],['Calculation Views & CDS Views','48:20'],['SQL Script & Procedures','34:15'],['Performance Optimization','28:44']] },
      { title: 'Kyma & Kubernetes on BTP', lessons: [['Kyma Runtime Overview','24:20'],['Deploying Microservices','38:22'],['Serverless Functions','26:18'],['Service Mesh & API Rules','32:12']] },
      { title: 'Integration Suite Essentials', lessons: [['iFlow Design Patterns','42:20'],['Integration with S/4HANA','48:15'],['API Management','34:22']] },
      { title: 'Extension Suite & Fiori', lessons: [['Side-by-Side Extensions','32:20'],['Fiori Elements & Freestyle','38:22'],['SAP Build Apps','28:44']] },
      { title: 'SAP AI Core & Business AI', lessons: [['AI Core Overview','24:20'],['Building AI Extensions','32:22'],['Joule & Business AI','28:18']] },
      { title: 'Security & Identity', lessons: [['XSUAA & IAS','28:20'],['OAuth 2.0 & JWT','24:15'],['Trust Configurations','22:40']] },
    ])
  },
  {
    slug: 'sap-cpi-integration-mastery',
    title: 'SAP Integration Suite (CPI) — Complete Mastery',
    subtitle: 'Build enterprise integrations end-to-end with real Indian corporate scenarios',
    category: 'sap-cpi', categoryName: 'SAP Integration Suite',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '38h', lectures: 96, students: 14820, rating: 4.9, reviews: 2812,
    price: 11999, originalPrice: 25999, discount: 54,
    thumbnail: 'https://images.unsplash.com/photo-1591439657848-9f4b9ce436b9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHw0fHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    banner: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['#1 Bestseller', 'Live Batches'],
    badge: 'Bestseller',
    description: 'India\'s #1 SAP Integration Suite course. Master iFlows, adapters, mapping, security, error handling, and enterprise integration patterns. Built by SAP Labs Bengaluru architects with real projects from TCS, Infosys, Deloitte India engagements.',
    whatYouLearn: [
      'Design and deploy enterprise iFlows on SAP Integration Suite',
      'Master all major adapters: HTTPS, SFTP, IDoc, SOAP, OData, JDBC',
      'Implement message mapping, groovy scripting, and content modifiers',
      'Apply OAuth 2.0, certificate-based auth, and security policies',
      'Debug, monitor, and optimize integration flows in production',
      'Integrate S/4HANA, SuccessFactors, Ariba, and 3rd-party systems',
      'Handle errors, retries, and dead-letter queues professionally',
      'Design for scale — throughput, parallelism, and observability',
    ],
    skills: ['SAP CPI', 'Integration Suite', 'iFlow Design', 'Groovy', 'Message Mapping', 'OAuth 2.0', 'S/4HANA'],
    instructor: { name: 'Rajesh Kumar', title: 'Principal SAP Integration Architect · Bengaluru', avatar: AV.rajesh, rating: 4.9, students: 28400, courses: 8, bio: '18 years architecting SAP integrations for Fortune 500 companies. Ex-SAP Labs Bengaluru.' },
    curriculum: mkCurriculum([
      { title: 'Getting Started with SAP Integration Suite', lessons: [['Introduction & Course Roadmap','8:12'],['Tenant Provisioning & Setup','14:20'],['Integration Suite UI Deep Dive','18:44']] },
      { title: 'Building Your First iFlow', lessons: [['Sender & Receiver Adapters','22:10'],['Message Processing Steps','28:35'],['Testing with Postman','15:50'],['Deployment & Monitoring','19:22']] },
      { title: 'Advanced Mapping & Scripting', lessons: [['Message Mapping Techniques','32:18'],['Groovy Script Essentials','41:22'],['Content Modifier Patterns','24:30'],['XSLT Transformations','28:14']] },
      { title: 'Security & Authentication', lessons: [['OAuth 2.0 in CPI','35:20'],['Certificate Management','22:40'],['Encryption & Signing','26:15']] },
      { title: 'Real-World Integration Scenarios', lessons: [['S/4HANA to Salesforce','48:20'],['SuccessFactors Employee Sync','52:10'],['Ariba PO Automation','44:00']] },
      { title: 'Error Handling & Monitoring', lessons: [['Exception Subprocesses','28:15'],['JMS Queues & Retry Logic','32:44'],['Splunk & Alerting','24:10']] },
    ])
  },
  {
    slug: 'sap-abap-on-hana-mastery',
    title: 'SAP ABAP on HANA — Modern ABAP Development',
    subtitle: 'CDS Views, AMDP, RAP (RESTful ABAP Programming) — for S/4HANA developers',
    category: 'sap-abap', categoryName: 'SAP ABAP',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '42h', lectures: 108, students: 18940, rating: 4.8, reviews: 3620,
    price: 9999, originalPrice: 21999, discount: 55,
    thumbnail: 'https://images.unsplash.com/photo-1665211097563-163d6be45d67?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwzfHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    banner: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Bestseller'], badge: 'Bestseller',
    description: 'Modern ABAP for the S/4HANA era. Master CDS Views, AMDP, RESTful ABAP Programming (RAP), OData services, and clean ABAP principles. Perfect for Indian ABAP consultants preparing for S/4HANA projects.',
    whatYouLearn: [
      'Master modern ABAP 7.5+ syntax and clean code principles',
      'Design CDS Views with associations, annotations, and virtual elements',
      'Build ABAP Managed Database Procedures (AMDP)',
      'Create OData services with RAP (RESTful ABAP Programming)',
      'Develop Fiori-ready business objects with behavior definitions',
      'Migrate custom code from ECC to S/4HANA (Code Remediation)',
      'Use Eclipse ADT and abapGit like a pro',
      'Debug HANA-specific issues and optimize SQL',
    ],
    skills: ['ABAP','CDS Views','AMDP','RAP','OData','S/4HANA','Eclipse ADT','abapGit'],
    instructor: { name: 'Suresh Iyer', title: 'S/4HANA Solution Architect · SAP Press Author · Chennai', avatar: AV.suresh, rating: 4.9, students: 34200, courses: 6, bio: '22 years in SAP development. Author of 3 SAP Press books on ABAP. Based in Chennai.' },
    curriculum: mkCurriculum([
      { title: 'Modern ABAP Foundations', lessons: [['Course Overview & Setup','10:20'],['ABAP 7.5+ New Syntax','32:15'],['Eclipse ADT Deep Dive','28:40'],['abapGit for Version Control','22:10']] },
      { title: 'CDS Views Mastery', lessons: [['CDS Fundamentals','32:20'],['Associations & Paths','44:15'],['Annotations Deep Dive','38:40'],['Analytical vs Transactional CDS','28:20']] },
      { title: 'AMDP & HANA Optimization', lessons: [['AMDP Fundamentals','32:12'],['SQLScript for ABAPers','48:20'],['Performance Tips','34:15']] },
      { title: 'RAP — RESTful ABAP Programming', lessons: [['RAP Architecture','28:20'],['Managed vs Unmanaged','38:22'],['Behavior Definitions & Implementations','48:18'],['Actions, Determinations & Validations','44:12']] },
      { title: 'OData & Fiori Integration', lessons: [['OData Services with RAP','32:20'],['Fiori Elements Consumption','38:22'],['Draft Handling','28:44']] },
      { title: 'S/4HANA Code Migration', lessons: [['Custom Code Migration Worklist','28:20'],['Simplification List','24:15'],['ATC Checks','22:40']] },
    ])
  },
  {
    slug: 'sap-fiori-ui5-development',
    title: 'SAP Fiori & UI5 Development — Build Enterprise Apps',
    subtitle: 'Fiori Elements, Freestyle SAPUI5, SAP Build Apps, deployment on BTP',
    category: 'sap-fiori', categoryName: 'SAP Fiori / UI5',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '36h', lectures: 92, students: 9240, rating: 4.8, reviews: 1740,
    price: 8999, originalPrice: 19999, discount: 55,
    thumbnail: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    banner: 'https://images.unsplash.com/photo-1541178735493-479c1a27ed24?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzh8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBsZWFybmluZ3xlbnwwfHx8Ymx1ZXwxNzg1MDQ1NzEyfDA&ixlib=rb-4.1.0&q=85',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Popular'], badge: 'Popular',
    description: 'Build enterprise-grade Fiori apps from scratch. Master Fiori Elements for annotation-driven development, freestyle UI5 for custom apps, and SAP Build Apps for low-code. Deploy to BTP with CI/CD.',
    whatYouLearn: [
      'Master SAPUI5 framework: MVC, data binding, controls',
      'Build List Report, Object Page, Analytical apps with Fiori Elements',
      'Extend Fiori apps with custom controllers & views',
      'Develop custom UI5 controls',
      'Configure Fiori Launchpad and role-based catalogs',
      'Deploy apps to BTP with piper/CI-CD pipelines',
      'Consume OData services & handle offline scenarios',
      'Build native mobile apps with SAP Build Apps (low-code)',
    ],
    skills: ['SAPUI5','Fiori Elements','OData','Business Application Studio','SAP Build','MTA','CI/CD'],
    instructor: { name: 'Anjali Desai', title: 'SAP Fiori UX Lead · Deloitte India · Mumbai', avatar: AV.anjali, rating: 4.9, students: 22600, courses: 5, bio: 'Ex-SAP Design Lead. 15 years building enterprise UX for Fortune 100 clients across India, UK, Singapore.' },
    curriculum: mkCurriculum([
      { title: 'Fiori Design & Architecture', lessons: [['Fiori Design Principles','18:20'],['Fiori vs UI5 vs Build Apps','24:15'],['Business Application Studio Setup','20:40']] },
      { title: 'SAPUI5 Fundamentals', lessons: [['MVC Pattern in UI5','32:20'],['Data Binding & Models','44:15'],['Routing & Navigation','38:40'],['Fragments & Reuse','28:20']] },
      { title: 'Fiori Elements Deep Dive', lessons: [['List Report App','32:12'],['Object Page','44:20'],['Analytical Apps','34:15'],['Annotation-Driven Development','38:44']] },
      { title: 'Custom UI5 Apps (Freestyle)', lessons: [['Freestyle App Structure','28:20'],['Custom Controllers','32:22'],['Custom Controls','28:18']] },
      { title: 'Deployment & Fiori Launchpad', lessons: [['MTA Projects & CF Deployment','32:20'],['Launchpad Configuration','28:22'],['Roles & Catalogs','22:44']] },
      { title: 'SAP Build Apps (Low-Code)', lessons: [['Build Apps Overview','24:20'],['Data Integration','28:22'],['Publishing to Mobile','22:18']] },
    ])
  },
  {
    slug: 'sap-successfactors-hcm-suite',
    title: 'SAP SuccessFactors — Complete HXM Suite',
    subtitle: 'Employee Central, Performance, Recruiting, Learning — Configure & Integrate',
    category: 'sap-successfactors', categoryName: 'SuccessFactors',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '44h', lectures: 118, students: 11180, rating: 4.7, reviews: 2020,
    price: 10999, originalPrice: 23999, discount: 54,
    thumbnail: 'https://images.pexels.com/photos/7689766/pexels-photo-7689766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    banner: 'https://images.pexels.com/photos/1181394/pexels-photo-1181394.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Popular','Certification'], badge: 'Popular',
    description: 'The complete SAP SuccessFactors HXM suite mastery. Cover Employee Central foundations, Performance & Goals, Recruiting, Onboarding 2.0, Learning, and end-to-end integrations with S/4HANA & third-party.',
    whatYouLearn: [
      'Configure Employee Central foundation & MDF objects',
      'Set up Position Management, Time Off, Benefits',
      'Implement Performance & Goals cycles',
      'Configure Recruiting Marketing & RCM',
      'Design Onboarding 2.0 flows',
      'Deploy Learning Management (LMS) with courses & curricula',
      'Integrate SF with S/4HANA using CPI standard packages',
      'Prepare for SF certification exams (C_THR8x series)',
    ],
    skills: ['Employee Central','MDF','RCM','Onboarding','LMS','Compensation','SF Integrations'],
    instructor: { name: 'Meera Nair', title: 'SF Solution Architect · 12x Certified · Hyderabad', avatar: AV.meera, rating: 4.8, students: 18400, courses: 7, bio: 'Ex-SAP SuccessFactors consultant. Trained 8,000+ SF professionals across India, UAE, and SEA.' },
    curriculum: mkCurriculum([
      { title: 'HXM Suite Overview', lessons: [['SF Architecture & Modules','20:20'],['Provisioning vs Admin Center','24:15'],['Data Model & Business Rules','28:40']] },
      { title: 'Employee Central Foundation', lessons: [['Foundation Objects','38:20'],['MDF Custom Objects','44:15'],['Workflows & Rules','48:40'],['Position Management','32:20']] },
      { title: 'Performance & Goals', lessons: [['PM Form Templates','32:12'],['360 Reviews','28:20'],['Calibration','24:15']] },
      { title: 'Recruiting & Onboarding', lessons: [['RCM Configuration','38:20'],['Onboarding 2.0 Flows','42:22'],['Offer Letter Templates','28:18']] },
      { title: 'Learning Management', lessons: [['Course Catalog','28:20'],['Curricula & Programs','32:22'],['Learning Assignments','24:44']] },
      { title: 'Integrations & Certification Prep', lessons: [['SF ↔ S/4HANA via CPI','32:20'],['Employee Central Compound Employee','28:22'],['Certification Roadmap','22:18']] },
    ])
  },
  {
    slug: 'aws-solutions-architect-pro',
    title: 'AWS Solutions Architect Professional — 2025',
    subtitle: 'Design fault-tolerant cloud architectures & pass the SAP-C02',
    category: 'aws', categoryName: 'AWS',
    level: 'Advanced', language: 'English + Hindi',
    duration: '52h', lectures: 128, students: 22240, rating: 4.8, reviews: 3820,
    price: 9999, originalPrice: 22999, discount: 57,
    thumbnail: 'https://images.unsplash.com/photo-1665211097563-163d6be45d67?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwzfHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    banner: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Popular', 'Certification'], badge: 'Popular',
    description: 'The gold-standard AWS SA Pro prep. Deep-dive into VPC design, high availability, security, cost optimization, and hybrid architectures — with 12 mock exams. Taught in English + Hindi.',
    whatYouLearn: ['Design multi-region VPC topologies','Implement zero-downtime migrations','Master IAM, KMS, GuardDuty & Security Hub','Optimize costs with Savings Plans & Compute Optimizer','Architect event-driven systems with EventBridge & Step Functions','Pass the SAP-C02 with confidence'],
    skills: ['AWS','VPC','EC2','Lambda','CloudFormation','IAM','Route53','Well-Architected'],
    instructor: { name: 'Priya Sharma', title: 'AWS Community Hero · 6x Certified · Pune', avatar: AV.priyaS, rating: 4.9, students: 62000, courses: 14, bio: 'Ex-AWS Solutions Architect India. Trained 50,000+ engineers across India & SEA.' },
    curriculum: mkCurriculum([
      { title: 'Foundations & Well-Architected Framework', lessons: [['Course Overview','6:30'],['5 Pillars Deep Dive','24:12'],['Shared Responsibility Model','18:40']] },
      { title: 'Networking & VPC Design', lessons: [['VPC Architecture Patterns','42:18'],['Transit Gateway','28:20'],['Direct Connect & Hybrid','34:12'],['PrivateLink','22:40']] },
      { title: 'Compute & Serverless', lessons: [['EC2 Advanced','38:15'],['Lambda Patterns','32:22'],['ECS vs EKS vs Fargate','44:10']] },
      { title: 'Storage & Databases', lessons: [['S3 Advanced','28:20'],['RDS Multi-AZ & Read Replicas','32:18'],['DynamoDB Global Tables','40:22']] },
      { title: 'Security & Compliance', lessons: [['IAM Deep Dive','38:44'],['KMS & Encryption','28:20'],['GuardDuty & Security Hub','24:10']] },
      { title: 'SAP-C02 Exam Prep', lessons: [['Exam Strategy','18:20'],['6 Full Mock Exams','120:00'],['Question Breakdowns','58:30']] },
    ])
  },
  {
    slug: 'genai-llm-engineering',
    title: 'GenAI & LLM Engineering — Build Production AI Apps',
    subtitle: 'From RAG pipelines to agentic workflows with GPT, Claude & Gemini',
    category: 'ai', categoryName: 'AI & GenAI',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '32h', lectures: 84, students: 16500, rating: 4.9, reviews: 3180,
    price: 13999, originalPrice: 29999, discount: 53,
    thumbnail: 'https://images.pexels.com/photos/7689766/pexels-photo-7689766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    banner: 'https://images.pexels.com/photos/1181394/pexels-photo-1181394.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['New','Trending'], badge: 'New',
    description: 'Master the full GenAI stack — prompt engineering, RAG, vector databases, agentic frameworks, evaluation, and deploying production LLM apps. Perfect for Indian engineers building GenAI products.',
    whatYouLearn: ['Build production RAG systems with pgvector & Pinecone','Design multi-agent workflows with LangGraph & CrewAI','Fine-tune open LLMs with LoRA/QLoRA','Implement guardrails, evals, and observability','Ship AI apps with Next.js, FastAPI & Vercel AI SDK','Optimize cost & latency across GPT-5, Claude 4.5, Gemini 3'],
    skills: ['LLMs','RAG','LangChain','Vector DBs','Prompt Engineering','Fine-Tuning','AI Agents'],
    instructor: { name: 'Dr. Aditya Menon', title: 'ML Engineer · Ex-DeepMind · Bengaluru', avatar: AV.aditya, rating: 4.9, students: 34500, courses: 6, bio: 'PhD in NLP from IIT Bombay + Stanford. Published in NeurIPS & ACL. Building AI products since 2018.' },
    curriculum: mkCurriculum([
      { title: 'LLM Fundamentals', lessons: [['Transformer Architecture','32:20'],['Tokenization & Embeddings','24:15'],['Modern LLM Landscape 2025','18:40']] },
      { title: 'Prompt Engineering Mastery', lessons: [['Zero/Few Shot Techniques','22:10'],['Chain of Thought & ReAct','28:30'],['Structured Outputs','20:15']] },
      { title: 'RAG Systems', lessons: [['Vector DBs Compared','34:22'],['Chunking Strategies','26:40'],['Hybrid Search','32:18'],['Advanced RAG Patterns','44:20']] },
      { title: 'Agentic AI', lessons: [['LangGraph Fundamentals','38:20'],['Multi-Agent Systems','42:44'],['Tool Use & Function Calling','30:20']] },
      { title: 'Production Deployment', lessons: [['Evals & Guardrails','32:22'],['Cost Optimization','24:18'],['Deploying on Vercel','28:15']] },
    ])
  },
  {
    slug: 'react-nextjs-fullstack',
    title: 'React & Next.js 15 — The Complete Full-Stack Course',
    subtitle: 'Ship production apps with Server Components, Actions & Turbopack',
    category: 'react', categoryName: 'React',
    level: 'All Levels', language: 'English + Hindi',
    duration: '42h', lectures: 118, students: 28800, rating: 4.8, reviews: 5240,
    price: 6999, originalPrice: 15999, discount: 56,
    thumbnail: 'https://images.unsplash.com/photo-1541178735493-479c1a27ed24?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzh8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBsZWFybmluZ3xlbnwwfHx8Ymx1ZXwxNzg1MDQ1NzEyfDA&ixlib=rb-4.1.0&q=85',
    banner: 'https://images.pexels.com/photos/89724/pexels-photo-89724.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Bestseller'], badge: 'Bestseller',
    description: 'From React fundamentals to shipping full-stack apps with Next.js 15 — Server Components, Actions, Streaming, Auth, Payments, and deployment.',
    whatYouLearn: ['React 19 & Server Components','Next.js 15 App Router mastery','Server Actions & data mutations','Auth with NextAuth v5','Stripe & Razorpay payments integration','Deploy on Vercel with edge functions'],
    skills: ['React','Next.js','TypeScript','Server Components','Tailwind','Auth.js','Stripe'],
    instructor: { name: 'Divya Iyengar', title: 'Senior Engineer · Ex-Razorpay · Bengaluru', avatar: AV.divya, rating: 4.8, students: 52000, courses: 12, bio: 'Building on React since 2015. Ex-Razorpay engineer. Speaks at React India & JSFoo.' },
    curriculum: mkCurriculum([
      { title: 'React 19 Fundamentals', lessons: [['Course Setup','8:20'],['Components & Props','24:12'],['Hooks Deep Dive','38:20']] },
      { title: 'Next.js 15 App Router', lessons: [['App Router Basics','22:10'],['Server vs Client Components','32:40'],['Data Fetching Patterns','28:30']] },
      { title: 'Server Actions & Forms', lessons: [['Actions Fundamentals','28:20'],['Optimistic Updates','24:18'],['Validation with Zod','22:40']] },
      { title: 'Auth & Payments', lessons: [['NextAuth Setup','32:20'],['Stripe & Razorpay Integration','48:22'],['Webhooks','26:18']] },
      { title: 'Deployment & Performance', lessons: [['Vercel Deploy','18:20'],['Edge Functions','24:40'],['Analytics','20:15']] },
    ])
  },
  {
    slug: 'devops-kubernetes-mastery',
    title: 'DevOps & Kubernetes — Zero to Production',
    subtitle: 'CI/CD, Docker, K8s, Terraform, GitOps with real pipelines',
    category: 'devops', categoryName: 'DevOps',
    level: 'Intermediate', language: 'English + Hindi',
    duration: '46h', lectures: 108, students: 19600, rating: 4.8, reviews: 2840,
    price: 8999, originalPrice: 19999, discount: 55,
    thumbnail: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    banner: 'https://images.unsplash.com/photo-1591439657848-9f4b9ce436b9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHw0fHxkZXZlbG9wZXIlMjBjb2Rpbmd8ZW58MHx8fGJsdWV8MTc4NTA0NTcxMnww&ixlib=rb-4.1.0&q=85',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Live Batches','Popular'], badge: 'Popular',
    description: 'Complete DevOps roadmap — Docker, Kubernetes, Terraform, ArgoCD, GitHub Actions, and observability with Prometheus + Grafana.',
    whatYouLearn: ['Containerize any app with Docker best practices','Deploy production K8s clusters (EKS/GKE/AKS)','Automate infra with Terraform modules','Build GitOps pipelines with ArgoCD','Setup Prometheus + Grafana observability','Master GitHub Actions & GitLab CI'],
    skills: ['Docker','Kubernetes','Terraform','ArgoCD','Prometheus','GitHub Actions','Helm'],
    instructor: { name: 'Vikram Reddy', title: 'Platform Engineer · CKA/CKS · Hyderabad', avatar: AV.vikram, rating: 4.8, students: 38000, courses: 9, bio: 'Building platforms for 12 years. Ex-Flipkart SRE. CNCF Ambassador.' },
    curriculum: mkCurriculum([
      { title: 'Docker Mastery', lessons: [['Docker Fundamentals','24:20'],['Multi-Stage Builds','28:15'],['Docker Compose','22:30']] },
      { title: 'Kubernetes Deep Dive', lessons: [['Cluster Architecture','32:12'],['Pods, Services, Ingress','48:20'],['Helm Charts','34:15']] },
      { title: 'Infrastructure as Code', lessons: [['Terraform Basics','28:22'],['Modules & State','32:40'],['AWS + Terraform','44:18']] },
      { title: 'CI/CD & GitOps', lessons: [['GitHub Actions','28:20'],['ArgoCD Setup','32:22'],['Progressive Delivery','26:18']] },
    ])
  },
  {
    slug: 'python-data-science-pro',
    title: 'Python for Data Science & ML — Complete Bootcamp',
    subtitle: 'NumPy, Pandas, Scikit-learn, PyTorch with 15 real projects',
    category: 'python', categoryName: 'Python',
    level: 'Beginner', language: 'English + Hindi',
    duration: '58h', lectures: 142, students: 42400, rating: 4.7, reviews: 8820,
    price: 5999, originalPrice: 13999, discount: 57,
    thumbnail: 'https://images.pexels.com/photos/1181394/pexels-photo-1181394.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    banner: 'https://images.pexels.com/photos/7689766/pexels-photo-7689766.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    promoVideo: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Bestseller','Beginner Friendly'], badge: 'Bestseller',
    description: 'The most complete Python + Data Science bootcamp. Zero to hire-ready with real projects: sales forecasting, image classification, NLP, and more.',
    whatYouLearn: ['Python from zero','Data wrangling with Pandas','Visualization: Matplotlib, Seaborn, Plotly','Classical ML with Scikit-learn','Deep Learning with PyTorch','Deploy models with FastAPI'],
    skills: ['Python','Pandas','NumPy','Scikit-learn','PyTorch','SQL','FastAPI'],
    instructor: { name: 'Dr. Kavya Sundaram', title: 'Lead Data Scientist · Ex-Flipkart · Bengaluru', avatar: AV.kavya, rating: 4.9, students: 84000, courses: 11, bio: 'PhD in Statistics from IIT Madras. 10 years in industry ML across Flipkart, Ola, and Swiggy.' },
    curriculum: mkCurriculum([
      { title: 'Python Fundamentals', lessons: [['Setup & IDE','12:20'],['Data Types & Control Flow','32:15'],['Functions & OOP','42:20']] },
      { title: 'Data Wrangling', lessons: [['NumPy Deep Dive','38:20'],['Pandas Essentials','48:40'],['Data Cleaning','32:15']] },
      { title: 'Machine Learning', lessons: [['Linear Regression','34:22'],['Classification','38:20'],['Trees & Ensembles','44:18']] },
      { title: 'Deep Learning', lessons: [['PyTorch Basics','38:20'],['CNNs for Vision','48:22'],['Transformers Intro','42:18']] },
    ])
  },
]

export const TESTIMONIALS = [
  { name: 'Arjun Patel', role: 'SAP Consultant → Integration Architect at Deloitte, Mumbai', avatar: AV.arjun, text: 'The SAP CPI course transformed my career. Went from junior consultant in Ahmedabad to architect at Deloitte Mumbai in 14 months. The real-world scenarios and hands-on labs were game-changing. Worth every rupee!', rating: 5, course: 'SAP Integration Suite' },
  { name: 'Priya Nair', role: 'SAP BTP Developer at Accenture, Bengaluru', avatar: AV.priyaS, text: 'IntegrationX Pro is THE place to learn SAP BTP in India. The CAP + Kyma modules gave me the confidence to lead our BTP migration project for a Fortune 500 client. Package doubled in 8 months!', rating: 5, course: 'SAP BTP Mastery' },
  { name: 'Karthik Reddy', role: 'ABAP Developer → S/4HANA Consultant at TCS, Hyderabad', avatar: AV.karthik, text: 'Suresh sir\'s ABAP on HANA course is the gold standard. Covered RAP and CDS Views better than any book. Passed S/4HANA certification on the first attempt and got promoted at TCS.', rating: 5, course: 'SAP ABAP on HANA' },
  { name: 'Sneha Menon', role: 'SuccessFactors Consultant at Capgemini, Chennai', avatar: AV.anjali, text: 'Best SuccessFactors training I have ever taken. Meera ma\'am explains configuration nuances that no other course teaches. Landed a senior SF role at Capgemini Chennai right after finishing.', rating: 5, course: 'SuccessFactors HXM' },
  { name: 'Rahul Verma', role: 'Fiori Developer at Infosys, Pune', avatar: AV.rajesh, text: 'From basic UI5 to shipping enterprise Fiori Elements apps in 3 months. The custom control section is pure gold. Highly recommended for anyone in Indian SAP ecosystem.', rating: 5, course: 'SAP Fiori / UI5' },
  { name: 'Aarti Krishnan', role: 'Data Scientist at Swiggy, Bengaluru', avatar: AV.meera, text: 'Dr. Kavya\'s Python bootcamp helped me switch from a service company to Swiggy as a Data Scientist. The projects are exactly what interviewers ask. Life-changing!', rating: 5, course: 'Python Data Science' },
]

export const LIVE_BATCHES = [
  { id: 'lb1', course: 'SAP BTP Complete Mastery', startDate: '2025-07-15', time: '7:00 PM IST', instructor: 'Rajesh Kumar', slug: 'sap-btp-complete-mastery', duration: '14 weekends', seats: 6 },
  { id: 'lb2', course: 'SAP Integration Suite (CPI)', startDate: '2025-07-22', time: '8:00 PM IST', instructor: 'Rajesh Kumar', slug: 'sap-cpi-integration-mastery', duration: '12 weekends', seats: 8 },
  { id: 'lb3', course: 'SAP ABAP on HANA', startDate: '2025-08-05', time: '7:30 PM IST', instructor: 'Suresh Iyer', slug: 'sap-abap-on-hana-mastery', duration: '12 weekends', seats: 10 },
  { id: 'lb4', course: 'SAP Fiori / UI5 Dev', startDate: '2025-08-12', time: '8:30 PM IST', instructor: 'Anjali Desai', slug: 'sap-fiori-ui5-development', duration: '10 weekends', seats: 12 },
]

export const FAQS = [
  { q: 'How long do I have access to the course?', a: 'Lifetime access. Once you enroll, the content, updates, and community are yours forever.' },
  { q: 'Are the certificates industry-recognized?', a: 'Yes. Our certificates include a unique verification ID, QR code, and are LinkedIn-shareable. Endorsed by 200+ hiring partners including TCS, Infosys, Wipro, Deloitte India, Accenture, and Capgemini.' },
  { q: 'What payment options do you support in India?', a: 'We accept UPI (GPay, PhonePe, Paytm), Net Banking, Credit/Debit Cards, EMI (3/6/9/12 months), and Razorpay wallet. All prices are inclusive of GST. Invoices are auto-generated.' },
  { q: 'Are courses in English or Hindi?', a: 'All courses are taught in English + Hindi hybrid (Hinglish). Slides & materials are in English. Instructor explanations mix English and Hindi to maximise clarity for Indian learners.' },
  { q: 'Do I need any prior experience?', a: 'Depends on the course — each listing shows the required level. We have offerings from complete beginner to advanced/architect level.' },
  { q: 'What if I am not satisfied?', a: '30-day no-questions-asked money-back guarantee. If it is not right for you, we refund 100% within 5-7 business days to your original payment method.' },
  { q: 'Do you offer corporate training?', a: 'Absolutely. We have trained teams at TCS, Infosys, Wipro, HCL, Tech Mahindra, Deloitte India, Accenture India and 40+ enterprises. Reach out via the Corporate section.' },
  { q: 'Are live classes recorded?', a: 'Yes, every live session is recorded and available in your dashboard within 2 hours. Attend from Mumbai, Bengaluru, Delhi, Hyderabad, Chennai, Pune — anywhere.' },
]

export function getCourseBySlug(slug) { return COURSES.find(c => c.slug === slug) }
export function getCoursesByCategory(cat) { return COURSES.filter(c => c.category === cat) }
