// Static Learning Paths — curated bundles that combine multiple courses
export const LEARNING_PATHS = [
  {
    slug: 'sap-integration-architect',
    title: 'SAP Integration Architect Roadmap',
    subtitle: 'From integration consultant to principal architect in 6 months',
    icon: '🏗️',
    color: 'from-blue-500 via-indigo-500 to-purple-500',
    duration: '6 months',
    level: 'Intermediate → Advanced',
    students: 3240,
    courseSlugs: ['sap-btp-complete-mastery', 'sap-cpi-integration-mastery', 'sap-abap-on-hana-mastery'],
    outcomes: [
      'Design & architect enterprise BTP + Integration Suite solutions',
      'Lead S/4HANA migration and integration projects',
      'Command 25-45 LPA salaries as an integration architect',
      'Consult for global SAP customers via Deloitte / Accenture / TCS',
    ],
    careerFor: ['SAP Consultants (3-8 years)', 'ABAP Developers wanting to move up', 'Basis / Technical Consultants'],
  },
  {
    slug: 'sap-hxm-specialist',
    title: 'SAP HXM & Fiori UX Specialist',
    subtitle: 'Master employee experience and modern SAP UI at once',
    icon: '👥',
    color: 'from-pink-500 via-rose-500 to-orange-500',
    duration: '4 months',
    level: 'Intermediate',
    students: 1820,
    courseSlugs: ['sap-successfactors-hcm-suite', 'sap-fiori-ui5-development'],
    outcomes: [
      'Configure & customize SuccessFactors end-to-end',
      'Build enterprise Fiori apps and extensions',
      'Deliver HR transformation projects for Fortune 500',
      'Command 18-32 LPA salaries as an HXM specialist',
    ],
    careerFor: ['HR Tech professionals', 'SF consultants wanting UX depth', 'Freelance SAP HR consultants'],
  },
  {
    slug: 'cloud-devops-engineer',
    title: 'Cloud & DevOps Engineer',
    subtitle: 'Ship reliable production systems on AWS with modern DevOps',
    icon: '☁️',
    color: 'from-emerald-500 via-teal-500 to-cyan-500',
    duration: '5 months',
    level: 'Intermediate',
    students: 5480,
    courseSlugs: ['aws-solutions-architect-pro', 'devops-kubernetes-mastery'],
    outcomes: [
      'Pass AWS SA Pro (SAP-C02) certification with confidence',
      'Design fault-tolerant multi-region architectures',
      'Master Kubernetes, Terraform, GitOps, and CI/CD',
      'Command 20-40 LPA at product companies & unicorns',
    ],
    careerFor: ['Backend engineers', 'System administrators', 'SREs & platform engineers'],
  },
  {
    slug: 'ai-engineer',
    title: 'AI & GenAI Engineer',
    subtitle: 'Zero to shipping production AI apps with LLMs & Python',
    icon: '🧠',
    color: 'from-purple-500 via-fuchsia-500 to-pink-500',
    duration: '4 months',
    level: 'Beginner → Advanced',
    students: 4210,
    courseSlugs: ['python-data-science-pro', 'genai-llm-engineering'],
    outcomes: [
      'Build production RAG apps & agentic workflows',
      'Fine-tune open LLMs with LoRA/QLoRA',
      'Ship AI features for real businesses',
      'Command 22-50 LPA at AI-first companies',
    ],
    careerFor: ['Software engineers pivoting to AI', 'Data analysts moving to ML', 'Product engineers'],
  },
]

export const getPathBySlug = (slug) => LEARNING_PATHS.find(p => p.slug === slug)
